modLoader="neoforge"
loaderVersion="[1.21.1,)"
license="MIT"
issueTrackerURL="https://github.com/SpaceRasser/clearlagg-1.21.1/issues"
[[mods]]
modId="clearlagmod"
version="${file.jarVersion}"
displayName="ClearLagMod"
authors="Rasser31"
description="Removes dropped items every 5 minutes."
dependencies = [
    { modId="neoforge", mandatory=true, versionRange="[21.1,22)", ordering="NONE", side="BOTH" }
]